# Generated by Django 6.0.3 on 2026-03-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_hora_hombre', models.DecimalField(decimal_places=2, default=25.0, max_digits=6)),
            ],
        ),
    ]
