# Generated by Django 6.0.3 on 2026-03-23 18:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fabricante', models.CharField(max_length=100)),
                ('nombre_modelo', models.CharField(max_length=100)),
                ('serial_fabricacion', models.CharField(max_length=100, unique=True)),
                ('id_empresarial_unico', models.CharField(max_length=100, unique=True)),
                ('precio_referencial', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='equipos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ParteModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_part', models.CharField(max_length=100)),
                ('numero_parte_fabricante', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('NUEVA', 'Nueva (Original)'), ('REPARADA', 'Reparada (Laboratorio)'), ('USADA', 'Usada (As-Is / Para Repara)'), ('SCRAP', 'Desecho / Canibalizada')], default='USADA', max_length=10)),
                ('costo_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock_disponible', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='partes_modulos/')),
                ('equipos_compatibles', models.ManyToManyField(related_name='partes_modulos', to='inventory.equipo')),
            ],
        ),
    ]
