# Generated by Django 6.0.3 on 2026-03-23 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parte_sp', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('fabricante_proveedor', models.CharField(max_length=100)),
                ('precio_dolares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('fecha_ingreso', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='small_parts/')),
            ],
        ),
        migrations.CreateModel(
            name='ReparacionModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_proceso', models.CharField(choices=[('RECIBIDO', 'Recibido / En Cola'), ('DIAGNOSTICO', 'En Diagnóstico'), ('ESPERA_PARTE', 'Pendiente por Small Parts (Faltante)'), ('EN_PROCESO', 'En Reparación Activa'), ('LISTO', 'Reparación Finalizada'), ('SIN_SOLUCION', 'No Reparable')], default='RECIBIDO', max_length=15)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('insumos_faltantes_notas', models.TextField(blank=True, help_text='¿Qué correas o piezas faltan?')),
                ('horas_hombre_empleadas', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('valor_hh_aplicado', models.DecimalField(decimal_places=2, default=25.0, max_digits=6)),
                ('parte_a_reparar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.partemodulo')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoSmallPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.reparacionmodulo')),
                ('small_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.smallpart')),
            ],
        ),
        migrations.AddField(
            model_name='reparacionmodulo',
            name='componentes_usados',
            field=models.ManyToManyField(through='lab.ConsumoSmallPart', to='lab.smallpart'),
        ),
    ]
