# Generated by Django 6.0.3 on 2026-03-26 20:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consumosmallpart',
            name='fecha_consumo',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumosmallpart',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reparacionmodulo',
            name='fecha_inicio_reparacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reparacionmodulo',
            name='fecha_irreparable',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reparacionmodulo',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reparacionmodulo',
            name='tecnico_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparaciones_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reparacionmodulo',
            name='estado_proceso',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('REVISION', 'Revisión'), ('EN_PROCESO', 'En Proceso'), ('LISTO', 'Listo'), ('IRREPARABLE', 'Irreparable')], default='INGRESO', max_length=15),
        ),
        migrations.AlterField(
            model_name='reparacionmodulo',
            name='horas_hombre_empleadas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='reparacionmodulo',
            name='valor_hh_aplicado',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=8),
        ),
        migrations.CreateModel(
            name='ReparacionModuloEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('INGRESO', 'Ingreso'), ('REVISION', 'Revisión'), ('EN_PROCESO', 'En Proceso'), ('LISTO', 'Listo'), ('IRREPARABLE', 'Irreparable')], max_length=15)),
                ('estado_nuevo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('REVISION', 'Revisión'), ('EN_PROCESO', 'En Proceso'), ('LISTO', 'Listo'), ('IRREPARABLE', 'Irreparable')], max_length=15)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True)),
                ('horas_hombre', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadocambio_set', to='lab.reparacionmodulo')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
